name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: darwin
          - os: windows-latest
            platform: windows
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.2'
        cache: true

    - name: Build binary (Linux/macOS)
      if: runner.os != 'Windows'
      run: go build -o ai-agents-cli .

    - name: Build binary (Windows)
      if: runner.os == 'Windows'
      run: go build -o ai-agents-cli.exe .

    - name: Upload artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ai-agents-cli-${{ matrix.platform }}
        path: |
          ai-agents-cli*
          !ai-agents-cli*.zip
        retention-days: 30

  docker:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/cloud-ru/ai-agents-cli
        tags: |
          type=ref,event=branch
          type=sha,prefix=commit-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

  release:
    runs-on: ubuntu-latest
    needs: [build, docker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest tag or set default
      id: get_version
      run: |
        # Получаем последний тег
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        if [ -z "$LATEST_TAG" ]; then
          # Если тегов нет, устанавливаем начальную версию
          echo "new_version=0.5.0" >> $GITHUB_OUTPUT
          echo "new_tag=v0.5.0" >> $GITHUB_OUTPUT
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v0.5.0
          git push origin v0.5.0
        else
          # Увеличиваем patch версию
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r major minor patch <<< "$VERSION"
          NEW_PATCH=$((patch + 1))
          NEW_VERSION="$major.$minor.$NEW_PATCH"
          NEW_TAG="v$NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
        fi

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.2'
        cache: true

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ai-agents-cli-*
        path: artifacts/

    - name: Prepare release files
      run: |
        mkdir -p release
        
        # Linux binary
        if [ -f artifacts/ai-agents-cli-linux/ai-agents-cli ]; then
          cp artifacts/ai-agents-cli-linux/ai-agents-cli release/ai-agents-cli-linux
          chmod +x release/ai-agents-cli-linux
        fi
        
        # macOS binary
        if [ -f artifacts/ai-agents-cli-darwin/ai-agents-cli ]; then
          cp artifacts/ai-agents-cli-darwin/ai-agents-cli release/ai-agents-cli-darwin
          chmod +x release/ai-agents-cli-darwin
        fi
        
        # Windows binary
        if [ -f artifacts/ai-agents-cli-windows/ai-agents-cli.exe ]; then
          cp artifacts/ai-agents-cli-windows/ai-agents-cli.exe release/ai-agents-cli-windows.exe
        fi
        
        echo "Release files:"
        ls -lah release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.new_tag }}
        draft: false
        prerelease: false
        files: release/*
        body: |
          ## Release ${{ steps.get_version.outputs.new_tag }}
          
          Automated build from main branch.
          
          ### Installation
          
          Download and extract the archive for your platform:
          - Linux: `ai-agents-cli-linux`
          - macOS: `ai-agents-cli-darwin`
          - Windows: `ai-agents-cli-windows.exe`
          
          ### Docker
          
          ```bash
          docker pull ghcr.io/cloud-ru/ai-agents-cli:${{ steps.get_version.outputs.new_version }}
          docker pull ghcr.io/cloud-ru/ai-agents-cli:latest
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
